/* =====================================================================
   КАТАЛОГ ТОВАРОВ ПИТОМНИКА «ДарЛес»
   ---------------------------------------------------------------------
   Проще всего менять этот файл через АДМИН-ПАНЕЛЬ: откройте admin.html —
   там фото добавляется перетаскиванием, а поля заполняются как форма.
   Количество (наличие) правится там же, в таблице «Наличие на складе».

   Каждое растение — блок { ... } в списке PRODUCTS, между блоками запятая.
     id  — уникальный номер (у нового: +1 к последнему)
     category — одно из: "hvoynye" | "listvennye" | "mnogoletnie"
     size  — размер (контейнер) из прайса, например "C3", "C7,5", "C10"
     price — розничная цена числом, без пробелов и ₽
     stock — количество в наличии, штук (null — «уточняйте»)
     image — путь к фото, например "images/catalog/23.jpg" ("" — фото пока нет)
     gallery — доп. фото: ["images/catalog/23-1.jpg"] или []
     short — короткая подпись в карточке
     description — абзацы разделяются пустой строкой ("" — описания пока нет)
   ===================================================================== */

const PRODUCTS = [
  {
    id: 10,
    name: "Можжевельник чешуйчатый «Blue Star»",
    category: "hvoynye",
    size: "",
    price: 900,
    stock: null,
    image: "images/catalog/10.jpg",
    gallery: [],
    short: "Компактная голубая подушка для рокария",
    description: `Можжевельник чешуйчатый «Blue Star» (Juniperus squamata Blue Star) — карликовый хвойник с плотной подушковидной кроной и очень яркой серебристо-голубой хвоей. Один из самых декоративных «голубых» можжевельников.

Высота взрослого растения — 40–60 см, ширина — до 1 метра. Растёт медленно, 5–8 см в год, поэтому долго сохраняет аккуратную форму. Зона морозостойкости — 4.

Требует солнечного места: только на открытом солнце хвоя приобретает насыщенный голубой тон. Почва — лёгкая, дренированная, слабокислая или нейтральная. Застой воды недопустим.

Уход: полив в засуху, мульчирование корой, весенняя подкормка для хвойных, санитарная обрезка. Молодые растения в первую зиму желательно притенять от февральского солнца.

Применение: альпинарии и рокарии, передний план хвойных композиций, японские и гравийные сады, контейнеры на террасе, невысокие бордюры.`
  },
  {
    id: 11,
    name: "Аукуба японская «Variegata»",
    category: "listvennye",
    size: "",
    price: 1400,
    stock: null,
    image: "images/catalog/11.jpg",
    gallery: [],
    short: "Вечнозелёный кустарник с «золотыми» листьями",
    description: `Аукуба японская «Variegata» (Aucuba japonica Variegata) — вечнозелёный кустарник с крупными кожистыми листьями, усыпанными золотисто-жёлтыми пятнами. За это её называют «золотым деревом».

Высота взрослого растения — 1,5–2 метра, крона плотная, округлая. Рост умеренный. Зона морозостойкости — 7: в приморском и предгорном Крыму зимует в открытом грунте, в более холодных регионах выращивается в кадке.

Главное достоинство — теневыносливость: аукуба прекрасно растёт в полутени и тени, где почти ничто не растёт. На прямом солнце листья бледнеют и обгорают. Почва — плодородная, влажная, дренированная.

Уход: регулярный полив, опрыскивание в жару, подкормки весной и летом, формирующая обрезка ранней весной.

Применение: озеленение теневых зон и северных стен, подлесок под крупными деревьями, зимние сады, кадочная культура для террас и входных групп.`
  },
  {
    id: 12,
    name: "Можжевельник средний «Variegata»",
    category: "hvoynye",
    size: "",
    price: 1100,
    stock: null,
    image: "images/catalog/12.jpg",
    gallery: [],
    short: "Раскидистый хвойник с кремовыми кончиками",
    description: `Можжевельник средний «Variegata» (Juniperus x media) — раскидистый хвойник с изящно приподнятыми побегами и пёстрой хвоей: тёмно-зелёной с кремово-белыми и золотистыми кончиками.

Высота взрослого растения — 1,5–2 метра, ширина кроны — до 3 метров. Годовой прирост — 15–20 см. Зона морозостойкости — 4.

Светолюбив: в тени пестролистность пропадает. К почвам нетребователен, отлично растёт на бедных, каменистых и известковых грунтах, засухоустойчив.

Уход: полив в первый сезон, весенняя подкормка, при необходимости — лёгкая формирующая стрижка. Побеги с чисто зелёной хвоей лучше вырезать, чтобы сохранить пестроту.

Применение: солитерные посадки на газоне, склоны и подпорные стенки, крупные хвойные композиции, цветовые акценты среди тёмно-зелёных растений.`
  },
  {
    id: 13,
    name: "Барбарис Тунберга",
    category: "listvennye",
    size: "",
    price: 600,
    stock: null,
    image: "images/catalog/13.jpg",
    gallery: [],
    short: "Огненная листва и колючая живая изгородь",
    description: `Барбарис Тунберга (Berberis thunbergii) — компактный листопадный кустарник с мелкими листьями, которые в течение сезона меняют окраску от алой и оранжевой до пурпурной, а осенью вспыхивают особенно ярко.

Высота взрослого растения — 1–1,5 метра. Рост умеренный. Зона морозостойкости — 4. Растение засухоустойчиво и хорошо переносит жару и городские условия.

Место — солнечное: в тени яркая окраска листвы теряется. Почва — любая дренированная, кислые грунты желательно известковать.

Уход: санитарная и формирующая обрезка весной, полив в сильную засуху, мульчирование. Колючие побеги делают куст отличной «защитной» изгородью.

Применение: низкие живые изгороди и бордюры, цветовые пятна в миксбордерах, рокарии, оформление дорожек и склонов.`
  },
  {
    id: 14,
    name: "Можжевельник казацкий",
    category: "hvoynye",
    size: "",
    price: 850,
    stock: null,
    image: "images/catalog/14.jpg",
    gallery: [],
    short: "Почвопокровный хвойник для склонов",
    description: `Можжевельник казацкий (Juniperus sabina) — стелющийся хвойник с широко раскинутыми побегами и насыщенно-зелёной чешуйчатой хвоей. Один из самых надёжных почвопокровных хвойных.

Высота — 0,5–1 метр, ширина разрастания — до 4–5 метров. Растёт быстро для хвойного. Зона морозостойкости — 3.

Исключительно неприхотлив: растёт на сухих, каменистых, известковых почвах, переносит жару, ветер и городскую пыль. Предпочитает солнце.

Уход: практически не требуется, при необходимости — ограничение разрастания обрезкой. Обратите внимание: побеги ядовиты, сажать вдали от детских площадок.

Применение: закрепление склонов и откосов, покровные массивы вместо газона, крупные рокарии, подпорные стенки, промышленное озеленение.`
  },
  {
    id: 15,
    name: "Можжевельник горизонтальный «Blue Chip»",
    category: "hvoynye",
    size: "",
    price: 950,
    stock: null,
    image: "images/catalog/15.jpg",
    gallery: [],
    short: "Голубой хвойный «ковёр»",
    description: `Можжевельник горизонтальный «Blue Chip» (Juniperus horizontalis Blue Chip) — стелющийся сорт с тонкими распростёртыми побегами и серебристо-голубой хвоей, которая зимой приобретает лиловый оттенок.

Высота — всего 25–30 см, ширина — до 1,5–2 метров. Рост медленный. Зона морозостойкости — 4.

Требует полного солнца и хорошего дренажа. Почвы — лёгкие, песчаные, бедные; на богатых и переувлажнённых растёт хуже.

Уход: полив в первый год, мульчирование гравием или корой, весенняя подкормка. Стрижка не нужна.

Применение: хвойные «ковры» и почвопокровные массивы, каскады через подпорные стенки, рокарии, контейнеры и приподнятые клумбы.`
  },
  {
    id: 16,
    name: "Можжевельник китайский",
    category: "hvoynye",
    size: "",
    price: 1000,
    stock: null,
    image: "images/catalog/16.jpg",
    gallery: [],
    short: "Пластичный хвойник для композиций",
    description: `Можжевельник китайский (Juniperus chinensis) — выносливый хвойник с приподнятыми ветвями и плотной ярко-зелёной хвоей. Универсален: хорошо смотрится и как солитер, и в группе.

Высота взрослого растения — 1,5–3 метра в зависимости от формы. Годовой прирост — 15–20 см. Зона морозостойкости — 4.

Светолюбив, но переносит лёгкую полутень. К почве нетребователен, важен только дренаж. Засухоустойчив, подходит для жаркого крымского климата.

Уход: полив в засуху, весенняя подкормка, формирующая стрижка — растение отлично держит форму и подходит для топиарной стрижки и садового бонсая.

Применение: живые изгороди, формованные фигуры, хвойные группы, оформление входных зон и парковок.`
  },
  {
    id: 17,
    name: "Гортензия крупнолистная",
    category: "listvennye",
    size: "",
    price: 1300,
    stock: null,
    image: "images/catalog/17.jpg",
    gallery: [],
    short: "Пышные шаровидные соцветия всё лето",
    description: `Гортензия крупнолистная (Hydrangea macrophylla) — эффектный кустарник с крупными шаровидными соцветиями розового, сиреневого или голубого оттенка. Цвет зависит от кислотности почвы: на кислой соцветия голубеют, на нейтральной — розовеют.

Высота куста — 1–1,5 метра. Цветение — с июня до сентября. Зона морозостойкости — 6: в Крыму зимует хорошо, в более холодных регионах требует укрытия, так как цветёт на побегах прошлого года.

Место — полутень, защищённое от полуденного солнца и ветра. Почва — рыхлая, кислая, влагоёмкая.

Уход: обильный полив (растение очень влаголюбиво), мульчирование, подкормки для гортензий, аккуратная обрезка только сухих соцветий и слабых побегов.

Применение: парадные клумбы и палисадники, посадки у стен и террас, контейнеры, срезка.`
  },
  {
    id: 18,
    name: "Фотиния Фразера «Red Robin»",
    category: "listvennye",
    size: "",
    price: 1600,
    stock: null,
    image: "images/catalog/18.jpg",
    gallery: [],
    short: "Вечнозелёный кустарник с алой молодой листвой",
    description: `Фотиния Фразера «Red Robin» (Photinia x fraseri Red Robin) — вечнозелёный кустарник, знаменитый огненно-красной молодой листвой, которая по мере взросления становится глянцево-зелёной. За сезон эффект повторяется несколько раз после каждой стрижки.

Высота взрослого растения — 2–3 метра, при формировке — до 4 метров. Рост быстрый: до 30 см в год. Зона морозостойкости — 7, идеально подходит для Крыма и юга России.

Место — солнце или лёгкая полутень, защита от холодных ветров. Почва — плодородная, дренированная, слабокислая.

Уход: стрижка 2–3 раза за сезон (она же стимулирует новые красные приросты), полив в засуху, подкормки весной и в середине лета.

Применение: вечнозелёные живые изгороди, штамбовые формы, акцентные солитеры, кадочные растения у входа.`
  },
  {
    id: 19,
    name: "Лагерстрёмия индийская",
    category: "listvennye",
    size: "",
    price: 2400,
    stock: null,
    image: "images/catalog/19.jpg",
    gallery: [],
    short: "«Индийская сирень» — цветение до осени",
    description: `Лагерстрёмия индийская (Lagerstroemia indica) — южное красивоцветущее дерево или крупный кустарник с эффектными гофрированными соцветиями малиновых, розовых, пурпурных и белых оттенков. Одно из лучших растений для крымского сада.

Высота — 2–5 метров в зависимости от формировки. Цветение — с июля до октября, когда большинство кустарников уже отцвели. Зона морозостойкости — 7.

Требует максимума солнца и тепла, защищённого от ветра места. Почва — дренированная, умеренно плодородная. Взрослое растение засухоустойчиво.

Уход: сильная весенняя обрезка прошлогодних побегов — она обеспечивает обильное цветение; полив в первые годы, подкормка весной. Декоративна и зимой благодаря гладкой «мраморной» коре.

Применение: акцентное дерево в центре композиции, аллеи в южных садах, штамбовые формы, кадочная культура.`
  },
  {
    id: 20,
    name: "Пеннисетум лисохвостный",
    category: "mnogoletnie",
    size: "",
    price: 450,
    stock: null,
    image: "images/catalog/20.jpg",
    gallery: [],
    short: "Декоративный злак с пушистыми колосками",
    description: `Пеннисетум лисохвостный (Pennisetum alopecuroides) — декоративный злак, образующий плотный фонтанообразный куст из узких листьев с пушистыми колосовидными соцветиями кремово-бежевого цвета.

Высота с соцветиями — 60–90 см. Цветение — с августа до заморозков; сухие колоски держатся на кусте всю зиму и красиво выглядят в инее. Зона морозостойкости — 5.

Место — солнечное, открытое. Почва — любая дренированная, злак засухоустойчив и не требует богатой земли.

Уход: обрезка куста «под ноль» ранней весной, деление раз в 4–5 лет. Полив только в затяжную засуху.

Применение: посадки в стиле «новая волна» и природные миксбордеры, массивы вдоль дорожек, соседство с очитками и эхинацеей, срезка и сухие букеты.`
  },
  {
    id: 21,
    name: "Просо прутьевидное",
    category: "mnogoletnie",
    size: "",
    price: 500,
    stock: null,
    image: "images/catalog/21.jpg",
    gallery: [],
    short: "Воздушный злак-вертикаль для миксбордера",
    description: `Просо прутьевидное (Panicum virgatum) — прямостоячий декоративный злак с сизо-зелёной листвой и лёгкими ажурными метёлками, создающими эффект «дымки» в композиции.

Высота — 1,2–1,8 метра. Метёлки появляются в июле–августе, осенью листва окрашивается в жёлто-охристые тона. Зона морозостойкости — 4.

Место — солнечное. Почва — любая, от песчаной до глинистой; растение переносит и засуху, и кратковременное переувлажнение.

Уход: обрезка сухих стеблей в конце зимы, деление куста раз в 5 лет. Подкормки не нужны — на жирной почве злак полегает.

Применение: вертикальные акценты и «живые ширмы» в миксбордерах, природные и злаковые сады, посадки у водоёмов, зимняя декоративность сада.`
  },
  {
    id: 22,
    name: "Хоста гибридная",
    category: "mnogoletnie",
    size: "",
    price: 400,
    stock: null,
    image: "images/catalog/22.jpg",
    gallery: [],
    short: "Главный многолетник для тенистых уголков",
    description: `Хоста гибридная (Hosta hybrida) — теневыносливый травянистый многолетник, который ценят за декоративную листву: от голубовато-сизой до золотистой и вариегатной.

Высота куста — 30–70 см в зависимости от сорта, ширина — до 80 см. Зона морозостойкости — 3. Долговечна: на одном месте растёт 15–20 лет.

Предпочитает полутень и тень, влажные плодородные почвы, богатые органикой. На ярком солнце листья выгорают.

Уход: регулярный полив, мульчирование, весенняя подкормка, защита от слизней. Деление куста — раз в 5–6 лет.

Применение: посадки под деревьями и с северной стороны построек, теневые миксбордеры, обрамление дорожек и водоёмов, контейнеры на затенённых террасах.`
  },
  {
    id: 23,
    name: "Азимина трёхлопастная (банановое дерево)",
    category: "listvennye",
    size: "C7,5",
    price: 2550,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 24,
    name: "Альбиция «Саммер шоколад»",
    category: "listvennye",
    size: "C10",
    price: 3300,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 25,
    name: "Аукуба «Кротонифолия»",
    category: "listvennye",
    size: "C3",
    price: 1000,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 26,
    name: "Барбарис тунберга «Ауреа»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 27,
    name: "Барбарис тунберга «Рэд Пилар»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 28,
    name: "Барбарис тунберга «Вениче»",
    category: "listvennye",
    size: "C3",
    price: 1200,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 29,
    name: "Барбарис тунберга «Голден Ринг»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 400,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 30,
    name: "Барбарис тунберга «Оранж Айс»",
    category: "listvennye",
    size: "C3",
    price: 1200,
    stock: 400,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 31,
    name: "Барбарис тунберга «Атропурпуреа Нана»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 32,
    name: "Барбарис тунберга «Багатель»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 150,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 33,
    name: "Барбарис тунберга «Коронита»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 34,
    name: "Барбарис Юлиана",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 35,
    name: "Берёза Повислая",
    category: "listvennye",
    size: "C10",
    price: 2250,
    stock: 115,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 36,
    name: "Берёза повислая «Ёнге»",
    category: "listvennye",
    size: "C10",
    price: 2700,
    stock: 135,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 37,
    name: "Берёза полезная «Дооренбоз»",
    category: "listvennye",
    size: "C10",
    price: 2700,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 38,
    name: "Бересклет японский «Альбамаргинатус»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 39,
    name: "Бересклет японский «Бенкомасаки»",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 400,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 40,
    name: "Бересклет японский «Оватус Ауреус»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 41,
    name: "Будлея Блэк Найт",
    category: "listvennye",
    size: "C3",
    price: 750,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 42,
    name: "Будлея Пинк Пантер",
    category: "listvennye",
    size: "C3",
    price: 750,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 43,
    name: "Бузина черная Вариегатта",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 44,
    name: "Бузина черная Тандерклауд",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 45,
    name: "Вейгела «Блэк энд Вайт»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 46,
    name: "Вейгела «Нана Вариегата»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 47,
    name: "Вейгела «Олд Саммер Рэд»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 48,
    name: "Вейгела «Пикобелла Роза»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 49,
    name: "Вейгела «Пинк Попет»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 50,
    name: "Вейгела «Александра»",
    category: "listvennye",
    size: "C3",
    price: 1150,
    stock: 80,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 51,
    name: "Вейгела «Ева Ратке»",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 52,
    name: "Витекс Священный",
    category: "listvennye",
    size: "C7,5",
    price: 1300,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 53,
    name: "Гаура «Бейби Батерфляй»",
    category: "mnogoletnie",
    size: "C3",
    price: 1050,
    stock: 75,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 54,
    name: "Гаура «Гамбит Компакт Пинк»",
    category: "mnogoletnie",
    size: "C3",
    price: 700,
    stock: 80,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 55,
    name: "Гаура «Пассионат Рейнбоу»",
    category: "mnogoletnie",
    size: "C3",
    price: 700,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 56,
    name: "Гейхера Кассис",
    category: "mnogoletnie",
    size: "C3",
    price: 750,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 57,
    name: "Гейхера Кримсон Керлс",
    category: "mnogoletnie",
    size: "C3",
    price: 750,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 58,
    name: "Гейхера Шуга Фростинг",
    category: "mnogoletnie",
    size: "C3",
    price: 750,
    stock: 170,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 59,
    name: "Гибискус сирийский «Блю Шифон» (голубой)",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 60,
    name: "Гибискус сирийский «Дюк Брабант» (ярко розовый)",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 61,
    name: "Гибискус сирийский «Френч кабаре парпл» (фиолет)",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 62,
    name: "Гибискус сирийский «Чайна Шифон» (бело розовый)",
    category: "listvennye",
    size: "C3",
    price: 1350,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 63,
    name: "Гибискус сирийский «Вайт Чифон» (белый)",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 64,
    name: "Гибискус сирийский «Пинк Чифон» (бледно розовый)",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 65,
    name: "Голубика «Блюкроп»",
    category: "listvennye",
    size: "C3",
    price: 1000,
    stock: 80,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 66,
    name: "Голубика «Патриот»",
    category: "listvennye",
    size: "C3",
    price: 1000,
    stock: 80,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 67,
    name: "Голубика «Дюке»",
    category: "listvennye",
    size: "C3",
    price: 1000,
    stock: 80,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 68,
    name: "Гортензия древовидная «Белла Анна»",
    category: "listvennye",
    size: "C5",
    price: 900,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 69,
    name: "Гортензия древовидная «Белла Рагаца Лиметта»",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 70,
    name: "Гортензия древовидная «Руби Анабель»",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 71,
    name: "Гортензия древовидная «Анабель»",
    category: "listvennye",
    size: "C5",
    price: 900,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 72,
    name: "Гортензия древовидная «Бабл Гамм»",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 73,
    name: "Гортензия древовидная «Маршмелоу»",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 74,
    name: "Гортензия крупнолистная «Никко Блю» (голубая)",
    category: "listvennye",
    size: "C5",
    price: 1150,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 75,
    name: "Гортензия крупнолистная «Мася» (розовая)",
    category: "listvennye",
    size: "C5",
    price: 1150,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 76,
    name: "Гортензия метельчатая «Бобо»",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 77,
    name: "Гортензия метельчатая «Ванила Фрайз»",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 78,
    name: "Гортензия метельчатая «Диамантино»",
    category: "listvennye",
    size: "C5",
    price: 900,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 79,
    name: "Гортензия метельчатая «Лайм лайт»",
    category: "listvennye",
    size: "C5",
    price: 900,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 80,
    name: "Гортензия метельчатая «Литл Блоссом»",
    category: "listvennye",
    size: "C5",
    price: 900,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 81,
    name: "Гортензия метельчатая «Пинки Винки»",
    category: "listvennye",
    size: "C5",
    price: 900,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 82,
    name: "Гортензия метельчатая «Самарская Лидия»",
    category: "listvennye",
    size: "C5",
    price: 900,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 83,
    name: "Гортензия метельчатая «Скайфол»",
    category: "listvennye",
    size: "C5",
    price: 900,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 84,
    name: "Гортензия метельчатая «Строубери Блоссом»",
    category: "listvennye",
    size: "C5",
    price: 900,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 85,
    name: "Гортензия метельчатая «Фрайз Мельба»",
    category: "listvennye",
    size: "C5",
    price: 900,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 86,
    name: "Дёрен белый Айвори Хало",
    category: "listvennye",
    size: "C3",
    price: 750,
    stock: 250,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 87,
    name: "Дёрен белый Гухалти",
    category: "listvennye",
    size: "C3",
    price: 750,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 88,
    name: "Дёрен белый Рэд Гном",
    category: "listvennye",
    size: "C3",
    price: 750,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 89,
    name: "Дёрен кроваво-красный Мидвинтер Файер",
    category: "listvennye",
    size: "C3",
    price: 750,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 90,
    name: "Ель «Нидиформис»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1000,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 91,
    name: "Ель «Дейзи Вайт»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1008,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 92,
    name: "Ель «Коника»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1008,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 93,
    name: "Ель «Сандерс Блю»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1008,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 94,
    name: "Ель «Эхиниформис»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 112,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 95,
    name: "Ель глаука «Альберта Глоб»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 224,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 96,
    name: "Ель Глаука Аризона Кейбаб",
    category: "hvoynye",
    size: "C3",
    price: 1000,
    stock: 1000,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 97,
    name: "Ель Глаука Глобоза",
    category: "hvoynye",
    size: "C5",
    price: 4000,
    stock: 400,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 98,
    name: "Ель колючая «Блю Диамант»",
    category: "hvoynye",
    size: "C5",
    price: 2550,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 99,
    name: "Ель колючая «Глаука Мейджик Блю»",
    category: "hvoynye",
    size: "C3",
    price: 1000,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 100,
    name: "Ель колючая «Глаука»",
    category: "hvoynye",
    size: "C3",
    price: 1000,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 101,
    name: "Ель колючая «Супер Блю Сидлинг»",
    category: "hvoynye",
    size: "C3",
    price: 2100,
    stock: 2000,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 102,
    name: "Ель колючая «Лаки Страйк»",
    category: "hvoynye",
    size: "C7,5",
    price: 4000,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 103,
    name: "Ель Обыкновенная",
    category: "hvoynye",
    size: "C3",
    price: 1000,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 104,
    name: "Ель сербская «Карел»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 112,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 105,
    name: "Ель Сербская (Оморика)",
    category: "hvoynye",
    size: "C3",
    price: 1000,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 106,
    name: "Жасмин голоцветковый",
    category: "listvennye",
    size: "C3",
    price: 750,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 107,
    name: "Земляничное дерево (Арбутус)",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 108,
    name: "Ива ломкая Булата",
    category: "listvennye",
    size: "C10",
    price: 2250,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 109,
    name: "Калина «Розеум» (Бульданеж)",
    category: "listvennye",
    size: "C3",
    price: 1000,
    stock: 120,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 110,
    name: "Калина лавролистная",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 111,
    name: "Калина лавролистная «Ева Прайс»",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 1940,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 112,
    name: "Кедр Атласский",
    category: "hvoynye",
    size: "C10",
    price: 2550,
    stock: 455,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 113,
    name: "Кедр Атласский глаука",
    category: "hvoynye",
    size: "C5",
    price: 3000,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 114,
    name: "Кедр Атласский глаука Пендула",
    category: "hvoynye",
    size: "C5",
    price: 3000,
    stock: 130,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 115,
    name: "Кедр Деодара",
    category: "hvoynye",
    size: "C10",
    price: 2550,
    stock: 345,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 116,
    name: "Кедр Деодара Пендула",
    category: "hvoynye",
    size: "C5",
    price: 3000,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 117,
    name: "Кедр Деодара Голден горизонт",
    category: "hvoynye",
    size: "C5",
    price: 3000,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 118,
    name: "Кедр Деодара Филин блю",
    category: "hvoynye",
    size: "C5",
    price: 3000,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 119,
    name: "Кедр Ливанский",
    category: "hvoynye",
    size: "C7,5",
    price: 2550,
    stock: 840,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 120,
    name: "Керрия японская Пленум",
    category: "listvennye",
    size: "C3",
    price: 700,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 121,
    name: "Кизильник Блестящий",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 122,
    name: "Кизильник Даммера",
    category: "listvennye",
    size: "C3",
    price: 750,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 123,
    name: "Кизильник Даммера «Миранда»",
    category: "listvennye",
    size: "C3",
    price: 750,
    stock: 1000,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 124,
    name: "Кипарис «Тотем»",
    category: "hvoynye",
    size: "C3",
    price: 1350,
    stock: 3000,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 125,
    name: "Кипарис Аризонский «Фастигиата»",
    category: "hvoynye",
    size: "C3",
    price: 1350,
    stock: 3500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 126,
    name: "Кипарис Аризонский «Глаука»",
    category: "hvoynye",
    size: "C3",
    price: 1350,
    stock: 675,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 127,
    name: "Кипарисовик Лавсона Вайт Спот",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 504,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 128,
    name: "Кипарисовик Лавсона Ван Пелтс Блю",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1008,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 129,
    name: "Кипарисовик Лавсона Ивон",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 504,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 130,
    name: "Кипарисовик тупой Драхт",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 216,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 131,
    name: "Кипарисовик тупой Нана Грацилис",
    category: "hvoynye",
    size: "C3",
    price: 1050,
    stock: 504,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 132,
    name: "Котовник Фассена Кит Кет",
    category: "mnogoletnie",
    size: "C3",
    price: 700,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 133,
    name: "Красивоплодник Бодиньера Профьюжен",
    category: "listvennye",
    size: "C3",
    price: 750,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 134,
    name: "Купрессоципарис Лейланда",
    category: "hvoynye",
    size: "C3",
    price: 900,
    stock: 11014,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 135,
    name: "Купрессоципарис Лейланда 2001 пирам",
    category: "hvoynye",
    size: "C3",
    price: 900,
    stock: 9016,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 136,
    name: "Купрессоципарис Лейланда Голд Райдер",
    category: "hvoynye",
    size: "C3",
    price: 900,
    stock: 2016,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 137,
    name: "Лаванда «Нана Альба»",
    category: "mnogoletnie",
    size: "C3",
    price: 850,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 138,
    name: "Лаванда «Розеа»",
    category: "mnogoletnie",
    size: "C3",
    price: 850,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 139,
    name: "Лаванда «Хидкод»",
    category: "mnogoletnie",
    size: "C3",
    price: 825,
    stock: 600,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 140,
    name: "Лаванда гибридная Гроссо",
    category: "mnogoletnie",
    size: "C3",
    price: 750,
    stock: 450,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 141,
    name: "Лаванда узколистная Розея",
    category: "mnogoletnie",
    size: "C3",
    price: 750,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 142,
    name: "Лавровишня луизитанская «Ангустифолия»",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 2000,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 143,
    name: "Лагерстремия «Берри Дазл» (розовая)",
    category: "listvennye",
    size: "C5",
    price: 1500,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 144,
    name: "Лагерстремия «Дабл Фатур» (ярко розовая)",
    category: "listvennye",
    size: "C5",
    price: 1500,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 145,
    name: "Лагерстремия «Рэд Император» (красная)",
    category: "listvennye",
    size: "C5",
    price: 1500,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 146,
    name: "Лагестремия Блек Диамант Кримсон Рэд (красная)",
    category: "listvennye",
    size: "C5",
    price: 2100,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 147,
    name: "Лагестремия Блек Диамант Блаш (белая)",
    category: "listvennye",
    size: "C5",
    price: 2100,
    stock: 250,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 148,
    name: "Лагестремия Блек Диамант Шел Пинк (розовая)",
    category: "listvennye",
    size: "C5",
    price: 2100,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 149,
    name: "Лох Узколистный",
    category: "listvennye",
    size: "C10",
    price: 2250,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 150,
    name: "Лох Эббинга",
    category: "listvennye",
    size: "C3",
    price: 1150,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 151,
    name: "Лох Эббинга «Глит Эйдж»",
    category: "listvennye",
    size: "C3",
    price: 1350,
    stock: 400,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 152,
    name: "Лох Эббинга «Компакта»",
    category: "listvennye",
    size: "C3",
    price: 1150,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 153,
    name: "Лох Эббинга «Лаймлайт»",
    category: "listvennye",
    size: "C3",
    price: 1350,
    stock: 160,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 154,
    name: "Лох Эббинга «Мерелин»",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 155,
    name: "Лох Эббинга «Вивилег»",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 700,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 156,
    name: "Магнолия вечнозеленая Литл Джем",
    category: "listvennye",
    size: "C7,5",
    price: 4000,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 157,
    name: "Магнолия Лебнера «Меррилл» (белая)",
    category: "listvennye",
    size: "C7,5",
    price: 1350,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 158,
    name: "Магнолия Суланжа (розово белая)",
    category: "listvennye",
    size: "C7,5",
    price: 1350,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 159,
    name: "Магнолия Суланжа «Джени» (темно розовая)",
    category: "listvennye",
    size: "C7,5",
    price: 3000,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 160,
    name: "Магнолия Суланжа «Орхид» (ярко розовая)",
    category: "listvennye",
    size: "C7,5",
    price: 1500,
    stock: 120,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 161,
    name: "Магнолия Суланжа «Сьюзан» звездчатая (розовая)",
    category: "listvennye",
    size: "C7,5",
    price: 1350,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 162,
    name: "Магнолия Суланжа «Гелакси» (розовая)",
    category: "listvennye",
    size: "C7,5",
    price: 1500,
    stock: 120,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 163,
    name: "Микробиота декусата",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 108,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 164,
    name: "Можжевельник вергинский «Хетц»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 2016,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 165,
    name: "Можжевельник вергинский «Грей Овл»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 166,
    name: "Можжевельник горизонт. «Вилтони»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1000,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 167,
    name: "Можжевельник горизонт. «Андора вариегата»",
    category: "hvoynye",
    size: "C3",
    price: 1000,
    stock: 1400,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 168,
    name: "Можжевельник горизонтальный «Андора Компакт»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1008,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 169,
    name: "Можжевельник горизонтальный «Блю Чип»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 4006,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 170,
    name: "Можжевельник горизонтальный «Принц Уэльский»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 3006,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 171,
    name: "Можжевельник казацкий «Блю Спаркл»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 172,
    name: "Можжевельник казацкий «Рокери Джем»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1600,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 173,
    name: "Можжевельник казацкий «Тамарисифолия»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 9018,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 174,
    name: "Можжевельник кит. «Стрикта вариегатная»",
    category: "hvoynye",
    size: "C3",
    price: 1000,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 175,
    name: "Можжевельник китайс. «Блю Альпс»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 414,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 176,
    name: "Можжевельник обыкновенный «Голдшатц»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 177,
    name: "Можжевельник обыкновенный «Грин Карпет»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 216,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 178,
    name: "Можжевельник прибрежный «Блю Пасифик»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1616,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 179,
    name: "Можжевельник прибрежный «Шлягер»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 918,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 180,
    name: "Можжевельник пфитцериана «Кинг оф Спринг»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 702,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 181,
    name: "Можжевельник пфитцериана «Ауреа»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1008,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 182,
    name: "Можжевельник пфитцериана «Глаука»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1116,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 183,
    name: "Можжевельник пфитцериана «Голд Кост»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 3006,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 184,
    name: "Можжевельник пфитцериана «Голд Стар»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 6066,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 185,
    name: "Можжевельник пфитцериана «Минт Джулепт»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 8010,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 186,
    name: "Можжевельник пфитцериана «Олд Голд»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 6002,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 187,
    name: "Можжевельник пфиц. «Пфецериана компакта»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1060,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 188,
    name: "Можжевельник скальный «Блю Эрроу»",
    category: "hvoynye",
    size: "C3",
    price: 1000,
    stock: 15012,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 189,
    name: "Можжевельник скальный «Мунглоу»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 9018,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 190,
    name: "Можжевельник чешуйчатый «Блю Шведе»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 504,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 191,
    name: "Можжевельник чешуйчатый «Блю Карпет»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 918,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 192,
    name: "Можжевельник чешуйчатый «Блю Стар»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1008,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 193,
    name: "Можжевельник чешуйчатый «Мейри»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1008,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 194,
    name: "Можжевельник чешуйчатый «Холгер»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 504,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 195,
    name: "Мушмула японская",
    category: "listvennye",
    size: "C7,5",
    price: 1650,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 196,
    name: "Павловния войлочная",
    category: "listvennye",
    size: "C10",
    price: 2250,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 197,
    name: "Падуб остролистный «Аргентеа Маргината»",
    category: "listvennye",
    size: "C3",
    price: 1000,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 198,
    name: "Пахисандра «Грин Карпет»",
    category: "mnogoletnie",
    size: "C3",
    price: 750,
    stock: 400,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 199,
    name: "Пахисандра «Вариегата»",
    category: "mnogoletnie",
    size: "C3",
    price: 750,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 200,
    name: "Пираканта «Рэд колумн»",
    category: "listvennye",
    size: "C3",
    price: 750,
    stock: 170,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 201,
    name: "Пихта Корейская «Сильберлок»",
    category: "hvoynye",
    size: "C5",
    price: 4500,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 202,
    name: "Пихта Нордмана",
    category: "hvoynye",
    size: "C3",
    price: 1350,
    stock: 20,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 203,
    name: "Пузыреплодник калинолистный «Ангел Голд»",
    category: "listvennye",
    size: "C3",
    price: 700,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 204,
    name: "Пузыреплодник калинолистный «Мэйджик Сансет»",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 205,
    name: "Пузыреплодник калинолистный «Саммер Вайн»",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 206,
    name: "Пузыреплодник калинолистный «Эмбер Джубили»",
    category: "listvennye",
    size: "C3",
    price: 1050,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 207,
    name: "Пузыреплодник калинолистный «Литл Девил»",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 208,
    name: "Ринкоспермум жасминовидный",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 209,
    name: "Рододендрон «Гейша Парпл» (сиреневый)",
    category: "listvennye",
    size: "C5",
    price: 1200,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 210,
    name: "Рододендрон «Марсель Минард» (фиолетовый)",
    category: "listvennye",
    size: "C5",
    price: 2250,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 211,
    name: "Рододендрон «Нова Зембла» (красный)",
    category: "listvennye",
    size: "C5",
    price: 2250,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 212,
    name: "Рододендрон «Рэд Джак» (красный)",
    category: "listvennye",
    size: "C5",
    price: 2250,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 213,
    name: "Розмарин «Корсикан Блю»",
    category: "mnogoletnie",
    size: "C3",
    price: 750,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 214,
    name: "Рябинник рябинолистный Сэм",
    category: "listvennye",
    size: "C5",
    price: 900,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 215,
    name: "Сирень «Мадам Лемуа»",
    category: "listvennye",
    size: "C5",
    price: 1150,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 216,
    name: "Сирень «Сенсация»",
    category: "listvennye",
    size: "C5",
    price: 1150,
    stock: 200,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 217,
    name: "Сирень «Чарльз Джоли»",
    category: "listvennye",
    size: "C5",
    price: 1150,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 218,
    name: "Скумпия «Роял Парпл»",
    category: "listvennye",
    size: "C5",
    price: 1350,
    stock: 400,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 219,
    name: "Сосна «Бенджамина»",
    category: "hvoynye",
    size: "C7,5",
    price: 6000,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 220,
    name: "Сосна «Орегон грин»",
    category: "hvoynye",
    size: "C7,5",
    price: 6000,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 221,
    name: "Сосна «Компакт Джем»",
    category: "hvoynye",
    size: "C7,5",
    price: 6000,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 222,
    name: "Сосна «Нигра»",
    category: "hvoynye",
    size: "C3",
    price: 1000,
    stock: 1000,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 223,
    name: "Сосна Алепская",
    category: "hvoynye",
    size: "C10",
    price: 1800,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 224,
    name: "Сосна горная «Малинки»",
    category: "hvoynye",
    size: "C7,5",
    price: 6000,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 225,
    name: "Сосна горная «Винтерголд»",
    category: "hvoynye",
    size: "C7,5",
    price: 6000,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 226,
    name: "Сосна горная «Карстенс Винтерголд»",
    category: "hvoynye",
    size: "C7,5",
    price: 6000,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 227,
    name: "Сосна горная «Мопс»",
    category: "hvoynye",
    size: "C7,5",
    price: 6000,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 228,
    name: "Сосна горная «Мугус»",
    category: "hvoynye",
    size: "C3",
    price: 900,
    stock: 504,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 229,
    name: "Сосна горная «Пумилио»",
    category: "hvoynye",
    size: "C3",
    price: 900,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 230,
    name: "Сосна горная Винтер голд",
    category: "hvoynye",
    size: "C5",
    price: 4000,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 231,
    name: "Сосна горная «Гном»",
    category: "hvoynye",
    size: "C5",
    price: 4000,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 232,
    name: "Сосна горная «Мопс»",
    category: "hvoynye",
    size: "C5",
    price: 4000,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 233,
    name: "Сосна Обыкновенная",
    category: "hvoynye",
    size: "C3",
    price: 1000,
    stock: 400,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 234,
    name: "Спирея японская «Голден Принцесс»",
    category: "listvennye",
    size: "C3",
    price: 700,
    stock: 800,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 235,
    name: "Спирея японская «Голдфлейм»",
    category: "listvennye",
    size: "C3",
    price: 700,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 236,
    name: "Спирея японская «Дабл Плей Биг-Бэнг Трейси»",
    category: "listvennye",
    size: "C3",
    price: 700,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 237,
    name: "Спирея японская «Литл Принцесс»",
    category: "listvennye",
    size: "C3",
    price: 700,
    stock: 800,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 238,
    name: "Спирея японская «Литл Флеим»",
    category: "listvennye",
    size: "C3",
    price: 700,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 239,
    name: "Спирея японская «Энтони Ватерер»",
    category: "listvennye",
    size: "C3",
    price: 700,
    stock: 700,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 240,
    name: "Стефанандра Криспа",
    category: "listvennye",
    size: "C3",
    price: 700,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 241,
    name: "Тамарикс",
    category: "listvennye",
    size: "C7,5",
    price: 1000,
    stock: 63,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 242,
    name: "Тамарикс Тетранда",
    category: "listvennye",
    size: "C7,5",
    price: 1000,
    stock: 2000,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 243,
    name: "Тис средний «Денсиформис»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 1008,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 244,
    name: "Тис средний «Хикси»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 504,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 245,
    name: "Тис средний «Хилли»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 1008,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 246,
    name: "Тис ягодный",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 308,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 247,
    name: "Тис ягодный «Давида»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 1512,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 248,
    name: "Тис ягодный «Репанденс»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 504,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 249,
    name: "Тис ягодный «Саммергольд»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 308,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 250,
    name: "Тис ягодный «Фастигиата Робуста»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 308,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 251,
    name: "Туя восточная «Ауреа нана»",
    category: "hvoynye",
    size: "C3",
    price: 900,
    stock: 7022,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 252,
    name: "Туя западная «Литл Гьянт»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 702,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 253,
    name: "Туя западная «Голден Брабант»",
    category: "hvoynye",
    size: "C3",
    price: 1100,
    stock: 504,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 254,
    name: "Туя западная «Голден Глоб»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 1008,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 255,
    name: "Туя западная «Мистер Боулинг Болл»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 702,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 256,
    name: "Туя западная «Рейнгольд»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 108,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 257,
    name: "Туя западная «Брабант»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 216,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 258,
    name: "Туя западная «Вудварди»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 1080,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 259,
    name: "Туя западная «Голден Таффет»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 216,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 260,
    name: "Туя западная «Даника»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 5004,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 261,
    name: "Туя западная «Мириам»",
    category: "hvoynye",
    size: "C3",
    price: 1150,
    stock: 1624,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 262,
    name: "Туя западная «Смарагд»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 13024,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 263,
    name: "Туя западная «Тини Тим»",
    category: "hvoynye",
    size: "C3",
    price: 750,
    stock: 2484,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 264,
    name: "Туя складчатая «Випкорд»",
    category: "hvoynye",
    size: "C3",
    price: 850,
    stock: 216,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 265,
    name: "Туя складчатая «Кагерс бьюти»",
    category: "hvoynye",
    size: "C3",
    price: 1000,
    stock: 700,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 266,
    name: "Туя складчатая «Форевер Голди»",
    category: "hvoynye",
    size: "C3",
    price: 1100,
    stock: 616,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 267,
    name: "Фейхоа",
    category: "listvennye",
    size: "C7,5",
    price: 1200,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 268,
    name: "Хеномелис «Пинк Трил»",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 115,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 269,
    name: "Хеномелис «Рэд Треил»",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 120,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 270,
    name: "Чубушник «Сноубель»",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 271,
    name: "Чубушник «Вирджинал»",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 272,
    name: "Чубушник Венечный",
    category: "listvennye",
    size: "C3",
    price: 900,
    stock: 100,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 273,
    name: "Эвкалипт «Беби Блю»",
    category: "listvennye",
    size: "C3",
    price: 1150,
    stock: 50,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 274,
    name: "Эскаллония Рубра Мачанта",
    category: "listvennye",
    size: "C3",
    price: 850,
    stock: 120,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 275,
    name: "Юкка глариоза «Вариегатта»",
    category: "mnogoletnie",
    size: "C7,5",
    price: 2550,
    stock: 500,
    image: "",
    gallery: [],
    short: "",
    description: ``
  },
  {
    id: 276,
    name: "Юкка рострата «Сапфир»",
    category: "mnogoletnie",
    size: "C5",
    price: 2850,
    stock: 300,
    image: "",
    gallery: [],
    short: "",
    description: ``
  }
];

/* Названия категорий — можно менять подписи, но НЕ ключи */
const CATEGORIES = {
  hvoynye:     { title: "Хвойные",     icon: "images/site/7.jpg" },
  listvennye:  { title: "Лиственные",  icon: "images/site/8.jpg" },
  mnogoletnie: { title: "Многолетние", icon: "images/site/9.jpg" }
};
