/* =====================================================================
   КАТАЛОГ ТОВАРОВ ПИТОМНИКА «ДарЛес»
   ---------------------------------------------------------------------
   ЭТО ЕДИНСТВЕННЫЙ ФАЙЛ, КОТОРЫЙ НУЖНО РЕДАКТИРОВАТЬ,
   ЧТОБЫ ДОБАВИТЬ / ИЗМЕНИТЬ / УДАЛИТЬ РАСТЕНИЕ В КАТАЛОГЕ.

   Каждый товар — это блок в фигурных скобках { ... }, между блоками — запятая.

   Поля:
     id          — номер по порядку (уникальный, просто +1 к последнему)
     name        — название растения, в кавычках
     category    — ровно одно из: "hvoynye" | "listvennye" | "mnogoletnie"
     price       — цена числом, без пробелов и без знака ₽  (например 1500)
     available   — true/false: есть ли растение в продаже.
     size        — размер контейнера (например "C3", "C5", "C7,5", "C10")
     qty         — количество на складе (число или null)
     image       — путь к главному фото, например "images/catalog/tuya.jpg"
     gallery     — доп. фото (можно оставить пустым: [])
     short       — короткая подпись под названием в карточке (1 строка)
     description — развёрнутое описание. Абзацы разделяются \n\n

   ВАЖНО: кавычки " внутри текста писать как \"  (со слэшем),
          либо использовать «ёлочки».
   ===================================================================== */

const PRODUCTS = [
  {
    id: 10,
    name: "Можжевельник чешуйчатый «Blue Star»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1008,
    image: "images/catalog/10.jpg",
    gallery: [],
    short: "Компактная голубая подушка для рокария",
    description: "Можжевельник чешуйчатый «Blue Star» (Juniperus squamata Blue Star) — карликовый хвойник с плотной подушковидной кроной и очень яркой серебристо-голубой хвоей. Один из самых декоративных «голубых» можжевельников.\n\nВысота взрослого растения — 40–60 см, ширина — до 1 метра. Растёт медленно, 5–8 см в год, поэтому долго сохраняет аккуратную форму. Зона морозостойкости — 4.\n\nТребует солнечного места: только на открытом солнце хвоя приобретает насыщенный голубой тон. Почва — лёгкая, дренированная, слабокислая или нейтральная. Застой воды недопустим.\n\nУход: полив в засуху, мульчирование корой, весенняя подкормка для хвойных, санитарная обрезка. Молодые растения в первую зиму желательно притенять от февральского солнца.\n\nПрименение: альпинарии и рокарии, передний план хвойных композиций, японские и гравийные сады, контейнеры на террасе, невысокие бордюры."
  },
  {
    id: 11,
    name: "Аукуба японская «Variegata»",
    category: "listvennye",
    price: 1400,
    available: true,
    size: "",
    qty: null,
    image: "images/catalog/11.jpg",
    gallery: [],
    short: "Вечнозелёный кустарник с «золотыми» листьями",
    description: "Аукуба японская «Variegata» (Aucuba japonica Variegata) — вечнозелёный кустарник с крупными кожистыми листьями, усыпанными золотисто-жёлтыми пятнами. За это её называют «золотым деревом».\n\nВысота взрослого растения — 1,5–2 метра, крона плотная, округлая. Рост умеренный. Зона морозостойкости — 7: в приморском и предгорном Крыму зимует в открытом грунте, в более холодных регионах выращивается в кадке.\n\nГлавное достоинство — теневыносливость: аукуба прекрасно растёт в полутени и тени, где почти ничто не растёт. На прямом солнце листья бледнеют и обгорают. Почва — плодородная, влажная, дренированная.\n\nУход: регулярный полив, опрыскивание в жару, подкормки весной и летом, формирующая обрезка ранней весной.\n\nПрименение: озеленение теневых зон и северных стен, подлесок под крупными деревьями, зимние сады, кадочная культура для террас и входных групп."
  },
  {
    id: 12,
    name: "Можжевельник средний «Variegata»",
    category: "hvoynye",
    price: 1100,
    available: true,
    size: "",
    qty: null,
    image: "images/catalog/12.jpg",
    gallery: [],
    short: "Раскидистый хвойник с кремовыми кончиками",
    description: "Можжевельник средний «Variegata» (Juniperus x media) — раскидистый хвойник с изящно приподнятыми побегами и пёстрой хвоей: тёмно-зелёной с кремово-белыми и золотистыми кончиками.\n\nВысота взрослого растения — 1,5–2 метра, ширина кроны — до 3 метров. Годовой прирост — 15–20 см. Зона морозостойкости — 4.\n\nСветолюбив: в тени пестролистность пропадает. К почвам нетребователен, отлично растёт на бедных, каменистых и известковых грунтах, засухоустойчив.\n\nУход: полив в первый сезон, весенняя подкормка, при необходимости — лёгкая формирующая стрижка. Побеги с чисто зелёной хвоей лучше вырезать, чтобы сохранить пестроту.\n\nПрименение: солитерные посадки на газоне, склоны и подпорные стенки, крупные хвойные композиции, цветовые акценты среди тёмно-зелёных растений."
  },
  {
    id: 13,
    name: "Барбарис Тунберга",
    category: "listvennye",
    price: 600,
    available: true,
    size: "",
    qty: null,
    image: "images/catalog/13.jpg",
    gallery: [],
    short: "Огненная листва и колючая живая изгородь",
    description: "Барбарис Тунберга (Berberis thunbergii) — компактный листопадный кустарник с мелкими листьями, которые в течение сезона меняют окраску от алой и оранжевой до пурпурной, а осенью вспыхивают особенно ярко.\n\nВысота взрослого растения — 1–1,5 метра. Рост умеренный. Зона морозостойкости — 4. Растение засухоустойчиво и хорошо переносит жару и городские условия.\n\nМесто — солнечное: в тени яркая окраска листвы теряется. Почва — любая дренированная, кислые грунты желательно известковать.\n\nУход: санитарная и формирующая обрезка весной, полив в сильную засуху, мульчирование. Колючие побеги делают куст отличной «защитной» изгородью.\n\nПрименение: низкие живые изгороди и бордюры, цветовые пятна в миксбордерах, рокарии, оформление дорожек и склонов."
  },
  {
    id: 14,
    name: "Можжевельник казацкий",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "",
    qty: null,
    image: "images/catalog/14.jpg",
    gallery: [],
    short: "Почвопокровный хвойник для склонов",
    description: "Можжевельник казацкий (Juniperus sabina) — стелющийся хвойник с широко раскинутыми побегами и насыщенно-зелёной чешуйчатой хвоей. Один из самых надёжных почвопокровных хвойных.\n\nВысота — 0,5–1 метр, ширина разрастания — до 4–5 метров. Растёт быстро для хвойного. Зона морозостойкости — 3.\n\nИсключительно неприхотлив: растёт на сухих, каменистых, известковых почвах, переносит жару, ветер и городскую пыль. Предпочитает солнце.\n\nУход: практически не требуется, при необходимости — ограничение разрастания обрезкой. Обратите внимание: побеги ядовиты, сажать вдали от детских площадок.\n\nПрименение: закрепление склонов и откосов, покровные массивы вместо газона, крупные рокарии, подпорные стенки, промышленное озеленение."
  },
  {
    id: 15,
    name: "Можжевельник горизонтальный «Blue Chip»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 4006,
    image: "images/catalog/15.jpg",
    gallery: [],
    short: "Голубой хвойный «ковёр»",
    description: "Можжевельник горизонтальный «Blue Chip» (Juniperus horizontalis Blue Chip) — стелющийся сорт с тонкими распростёртыми побегами и серебристо-голубой хвоей, которая зимой приобретает лиловый оттенок.\n\nВысота — всего 25–30 см, ширина — до 1,5–2 метров. Рост медленный. Зона морозостойкости — 4.\n\nТребует полного солнца и хорошего дренажа. Почвы — лёгкие, песчаные, бедные; на богатых и переувлажнённых растёт хуже.\n\nУход: полив в первый год, мульчирование гравием или корой, весенняя подкормка. Стрижка не нужна.\n\nПрименение: хвойные «ковры» и почвопокровные массивы, каскады через подпорные стенки, рокарии, контейнеры и приподнятые клумбы."
  },
  {
    id: 16,
    name: "Можжевельник китайский",
    category: "hvoynye",
    price: 1000,
    available: true,
    size: "",
    qty: null,
    image: "images/catalog/16.jpg",
    gallery: [],
    short: "Пластичный хвойник для композиций",
    description: "Можжевельник китайский (Juniperus chinensis) — выносливый хвойник с приподнятыми ветвями и плотной ярко-зелёной хвоей. Универсален: хорошо смотрится и как солитер, и в группе.\n\nВысота взрослого растения — 1,5–3 метра в зависимости от формы. Годовой прирост — 15–20 см. Зона морозостойкости — 4.\n\nСветолюбив, но переносит лёгкую полутень. К почве нетребователен, важен только дренаж. Засухоустойчив, подходит для жаркого крымского климата.\n\nУход: полив в засуху, весенняя подкормка, формирующая стрижка — растение отлично держит форму и подходит для топиарной стрижки и садового бонсая.\n\nПрименение: живые изгороди, формованные фигуры, хвойные группы, оформление входных зон и парковок."
  },
  {
    id: 17,
    name: "Гортензия крупнолистная",
    category: "listvennye",
    price: 1300,
    available: true,
    size: "",
    qty: null,
    image: "images/catalog/17.jpg",
    gallery: [],
    short: "Пышные шаровидные соцветия всё лето",
    description: "Гортензия крупнолистная (Hydrangea macrophylla) — эффектный кустарник с крупными шаровидными соцветиями розового, сиреневого или голубого оттенка. Цвет зависит от кислотности почвы: на кислой соцветия голубеют, на нейтральной — розовеют.\n\nВысота куста — 1–1,5 метра. Цветение — с июня до сентября. Зона морозостойкости — 6: в Крыму зимует хорошо, в более холодных регионах требует укрытия, так как цветёт на побегах прошлого года.\n\nМесто — полутень, защищённое от полуденного солнца и ветра. Почва — рыхлая, кислая, влагоёмкая.\n\nУход: обильный полив (растение очень влаголюбиво), мульчирование, подкормки для гортензий, аккуратная обрезка только сухих соцветий и слабых побегов.\n\nПрименение: парадные клумбы и палисадники, посадки у стен и террас, контейнеры, срезка."
  },
  {
    id: 18,
    name: "Фотиния Фразера «Red Robin»",
    category: "listvennye",
    price: 1600,
    available: true,
    size: "",
    qty: null,
    image: "images/catalog/18.jpg",
    gallery: [],
    short: "Вечнозелёный кустарник с алой молодой листвой",
    description: "Фотиния Фразера «Red Robin» (Photinia x fraseri Red Robin) — вечнозелёный кустарник, знаменитый огненно-красной молодой листвой, которая по мере взросления становится глянцево-зелёной. За сезон эффект повторяется несколько раз после каждой стрижки.\n\nВысота взрослого растения — 2–3 метра, при формировке — до 4 метров. Рост быстрый: до 30 см в год. Зона морозостойкости — 7, идеально подходит для Крыма и юга России.\n\nМесто — солнце или лёгкая полутень, защита от холодных ветров. Почва — плодородная, дренированная, слабокислая.\n\nУход: стрижка 2–3 раза за сезон (она же стимулирует новые красные приросты), полив в засуху, подкормки весной и в середине лета.\n\nПрименение: вечнозелёные живые изгороди, штамбовые формы, акцентные солитеры, кадочные растения у входа."
  },
  {
    id: 19,
    name: "Лагерстрёмия индийская",
    category: "listvennye",
    price: 2400,
    available: true,
    size: "",
    qty: null,
    image: "images/catalog/19.jpg",
    gallery: [],
    short: "«Индийская сирень» — цветение до осени",
    description: "Лагерстрёмия индийская (Lagerstroemia indica) — южное красивоцветущее дерево или крупный кустарник с эффектными гофрированными соцветиями малиновых, розовых, пурпурных и белых оттенков. Одно из лучших растений для крымского сада.\n\nВысота — 2–5 метров в зависимости от формировки. Цветение — с июля до октября, когда большинство кустарников уже отцвели. Зона морозостойкости — 7.\n\nТребует максимума солнца и тепла, защищённого от ветра места. Почва — дренированная, умеренно плодородная. Взрослое растение засухоустойчиво.\n\nУход: сильная весенняя обрезка прошлогодних побегов — она обеспечивает обильное цветение; полив в первые годы, подкормка весной. Декоративна и зимой благодаря гладкой «мраморной» коре.\n\nПрименение: акцентное дерево в центре композиции, аллеи в южных садах, штамбовые формы, кадочная культура."
  },
  {
    id: 20,
    name: "Пеннисетум лисохвостный",
    category: "mnogoletnie",
    price: 450,
    available: true,
    size: "",
    qty: null,
    image: "images/catalog/20.jpg",
    gallery: [],
    short: "Декоративный злак с пушистыми колосками",
    description: "Пеннисетум лисохвостный (Pennisetum alopecuroides) — декоративный злак, образующий плотный фонтанообразный куст из узких листьев с пушистыми колосовидными соцветиями кремово-бежевого цвета.\n\nВысота с соцветиями — 60–90 см. Цветение — с августа до заморозков; сухие колоски держатся на кусте всю зиму и красиво выглядят в инее. Зона морозостойкости — 5.\n\nМесто — солнечное, открытое. Почва — любая дренированная, злак засухоустойчив и не требует богатой земли.\n\nУход: обрезка куста «под ноль» ранней весной, деление раз в 4–5 лет. Полив только в затяжную засуху.\n\nПрименение: посадки в стиле «новая волна» и природные миксбордеры, массивы вдоль дорожек, соседство с очитками и эхинацеей, срезка и сухие букеты."
  },
  {
    id: 21,
    name: "Просо прутьевидное",
    category: "mnogoletnie",
    price: 500,
    available: true,
    size: "",
    qty: null,
    image: "images/catalog/21.jpg",
    gallery: [],
    short: "Воздушный злак-вертикаль для миксбордера",
    description: "Просо прутьевидное (Panicum virgatum) — прямостоячий декоративный злак с сизо-зелёной листвой и лёгкими ажурными метёлками, создающими эффект «дымки» в композиции.\n\nВысота — 1,2–1,8 метра. Метёлки появляются в июле–августе, осенью листва окрашивается в жёлто-охристые тона. Зона морозостойкости — 4.\n\nМесто — солнечное. Почва — любая, от песчаной до глинистой; растение переносит и засуху, и кратковременное переувлажнение.\n\nУход: обрезка сухих стеблей в конце зимы, деление куста раз в 5 лет. Подкормки не нужны — на жирной почве злак полегает.\n\nПрименение: вертикальные акценты и «живые ширмы» в миксбордерах, природные и злаковые сады, посадки у водоёмов, зимняя декоративность сада."
  },
  {
    id: 22,
    name: "Хоста гибридная",
    category: "mnogoletnie",
    price: 400,
    available: true,
    size: "",
    qty: null,
    image: "images/catalog/22.jpg",
    gallery: [],
    short: "Главный многолетник для тенистых уголков",
    description: "Хоста гибридная (Hosta hybrida) — теневыносливый травянистый многолетник, который ценят за декоративную листву: от голубовато-сизой до золотистой и вариегатной.\n\nВысота куста — 30–70 см в зависимости от сорта, ширина — до 80 см. Зона морозостойкости — 3. Долговечна: на одном месте растёт 15–20 лет.\n\nПредпочитает полутень и тень, влажные плодородные почвы, богатые органикой. На ярком солнце листья выгорают.\n\nУход: регулярный полив, мульчирование, весенняя подкормка, защита от слизней. Деление куста — раз в 5–6 лет.\n\nПрименение: посадки под деревьями и с северной стороны построек, теневые миксбордеры, обрамление дорожек и водоёмов, контейнеры на затенённых террасах."
  },
  {
    id: 23,
    name: "Азимина трёхлопастная",
    category: "listvennye",
    price: 2550,
    available: true,
    size: "C7,5",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Банановое дерево",
    description: ""
  },
  {
    id: 24,
    name: "Альбиция «Саммер Шоколад»",
    category: "listvennye",
    price: 3300,
    available: true,
    size: "C10",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C10",
    description: ""
  },
  {
    id: 25,
    name: "Аукуба японская «Кротонифолия»",
    category: "listvennye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 26,
    name: "Барбарис Тунберга «Ауреа»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 27,
    name: "Барбарис Тунберга «Рэд Пилар»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 28,
    name: "Барбарис Тунберга «Вениче»",
    category: "listvennye",
    price: 1200,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 29,
    name: "Барбарис Тунберга «Голден Ринг»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 400,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 30,
    name: "Барбарис Тунберга «Оранж Айс»",
    category: "listvennye",
    price: 1200,
    available: true,
    size: "C3",
    qty: 400,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 31,
    name: "Барбарис Тунберга «Атропурпуреа Нана»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 32,
    name: "Барбарис Тунберга «Багатель»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 150,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 33,
    name: "Барбарис Тунберга «Коронита»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 34,
    name: "Барбарис Юлиана",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 35,
    name: "Берёза повислая",
    category: "listvennye",
    price: 2250,
    available: true,
    size: "C10",
    qty: 115,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C10",
    description: ""
  },
  {
    id: 36,
    name: "Берёза повислая «Ёнге»",
    category: "listvennye",
    price: 2700,
    available: true,
    size: "C10",
    qty: 135,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C10",
    description: ""
  },
  {
    id: 37,
    name: "Берёза полезная «Дооренбоз»",
    category: "listvennye",
    price: 2700,
    available: true,
    size: "C10",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C10",
    description: ""
  },
  {
    id: 38,
    name: "Бересклет японский «Альбомаргинатус»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 39,
    name: "Бересклет японский «Бенкомасаки»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 400,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 40,
    name: "Бересклет японский «Оватус Ауреус»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 41,
    name: "Будлея «Блэк Найт»",
    category: "listvennye",
    price: 750,
    available: true,
    size: "C3",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 42,
    name: "Будлея «Пинк Пантер»",
    category: "listvennye",
    price: 750,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 43,
    name: "Бузина чёрная «Вариегата»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 44,
    name: "Бузина чёрная «Тандерклауд»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 45,
    name: "Вейгела «Блэк энд Вайт»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 46,
    name: "Вейгела «Нана Вариегата»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 47,
    name: "Вейгела «Олл Саммер Рэд»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 48,
    name: "Вейгела «Пикобелла Роза»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 49,
    name: "Вейгела «Пинк Поппет»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 50,
    name: "Вейгела «Александра»",
    category: "listvennye",
    price: 1150,
    available: true,
    size: "C3",
    qty: 80,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 51,
    name: "Вейгела «Ева Ратке»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 52,
    name: "Витекс священный",
    category: "listvennye",
    price: 1300,
    available: true,
    size: "C7,5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 53,
    name: "Гаура «Бейби Баттерфляй»",
    category: "mnogoletnie",
    price: 1050,
    available: true,
    size: "C3",
    qty: 75,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 54,
    name: "Гаура «Гамбит Компакт Пинк»",
    category: "mnogoletnie",
    price: 700,
    available: true,
    size: "C3",
    qty: 80,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 55,
    name: "Гаура «Пассионат Рейнбоу»",
    category: "mnogoletnie",
    price: 700,
    available: true,
    size: "C3",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 56,
    name: "Гейхера «Кассис»",
    category: "mnogoletnie",
    price: 750,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 57,
    name: "Гейхера «Кримсон Кёрлс»",
    category: "mnogoletnie",
    price: 750,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 58,
    name: "Гейхера «Шуга Фростинг»",
    category: "mnogoletnie",
    price: 750,
    available: true,
    size: "C3",
    qty: 170,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 59,
    name: "Гибискус сирийский «Блю Шифон»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Голубые цветки",
    description: ""
  },
  {
    id: 60,
    name: "Гибискус сирийский «Дюк де Брабант»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Ярко-розовые цветки",
    description: ""
  },
  {
    id: 61,
    name: "Гибискус сирийский «Френч Кабаре Парпл»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Фиолетовые цветки",
    description: ""
  },
  {
    id: 62,
    name: "Гибискус сирийский «Чайна Шифон»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Бело-розовые цветки",
    description: ""
  },
  {
    id: 63,
    name: "Гибискус сирийский «Вайт Шифон»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Белые цветки",
    description: ""
  },
  {
    id: 64,
    name: "Гибискус сирийский «Пинк Шифон»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Бледно-розовые цветки",
    description: ""
  },
  {
    id: 65,
    name: "Голубика «Блюкроп»",
    category: "listvennye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 80,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 66,
    name: "Голубика «Патриот»",
    category: "listvennye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 80,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 67,
    name: "Голубика «Дюк»",
    category: "listvennye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 80,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 68,
    name: "Гортензия древовидная «Белла Анна»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 69,
    name: "Гортензия древовидная «Белла Рагацца Лиметта»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 70,
    name: "Гортензия древовидная «Руби Аннабель»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 71,
    name: "Гортензия древовидная «Аннабель»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 72,
    name: "Гортензия древовидная «Бабл Гам»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 73,
    name: "Гортензия древовидная «Маршмеллоу»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 74,
    name: "Гортензия крупнолистная «Никко Блю»",
    category: "listvennye",
    price: 1150,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Голубые соцветия",
    description: ""
  },
  {
    id: 75,
    name: "Гортензия крупнолистная «Мася»",
    category: "listvennye",
    price: 1150,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Розовые соцветия",
    description: ""
  },
  {
    id: 76,
    name: "Гортензия метельчатая «Бобо»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 77,
    name: "Гортензия метельчатая «Ванила Фрайз»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 78,
    name: "Гортензия метельчатая «Диамантино»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 79,
    name: "Гортензия метельчатая «Лаймлайт»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C5",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 80,
    name: "Гортензия метельчатая «Литл Блоссом»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 81,
    name: "Гортензия метельчатая «Пинки Винки»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 82,
    name: "Гортензия метельчатая «Самарская Лидия»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 83,
    name: "Гортензия метельчатая «Скайфолл»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 84,
    name: "Гортензия метельчатая «Строубери Блоссом»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 85,
    name: "Гортензия метельчатая «Фрайз Мельба»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 86,
    name: "Дёрен белый «Айвори Хало»",
    category: "listvennye",
    price: 750,
    available: true,
    size: "C3",
    qty: 250,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 87,
    name: "Дёрен белый «Гухалти»",
    category: "listvennye",
    price: 750,
    available: true,
    size: "C3",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 88,
    name: "Дёрен белый «Рэд Гном»",
    category: "listvennye",
    price: 750,
    available: true,
    size: "C3",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 89,
    name: "Дёрен кроваво-красный «Мидвинтер Файер»",
    category: "listvennye",
    price: 750,
    available: true,
    size: "C3",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 90,
    name: "Ель обыкновенная «Нидиформис»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1000,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 91,
    name: "Ель сизая «Дейзи Вайт»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1008,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 92,
    name: "Ель сизая «Коника»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1008,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 93,
    name: "Ель сизая «Сандерс Блю»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1008,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 94,
    name: "Ель сизая «Эхиниформис»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 112,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 95,
    name: "Ель сизая «Альберта Глоб»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 224,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 96,
    name: "Ель колючая «Глаука Аризона Кейбаб»",
    category: "hvoynye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 1000,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 97,
    name: "Ель колючая «Глаука Глобоза»",
    category: "hvoynye",
    price: 4000,
    available: true,
    size: "C5",
    qty: 400,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 98,
    name: "Ель колючая «Блю Диамант»",
    category: "hvoynye",
    price: 2550,
    available: true,
    size: "C5",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 99,
    name: "Ель колючая «Глаука Мейджик Блю»",
    category: "hvoynye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 100,
    name: "Ель колючая «Глаука»",
    category: "hvoynye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 101,
    name: "Ель колючая «Супер Блю Сидлинг»",
    category: "hvoynye",
    price: 2100,
    available: true,
    size: "C3",
    qty: 2000,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 102,
    name: "Ель колючая «Лаки Страйк»",
    category: "hvoynye",
    price: 4000,
    available: true,
    size: "C7,5",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 103,
    name: "Ель обыкновенная",
    category: "hvoynye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 104,
    name: "Ель сербская «Карел»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 112,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 105,
    name: "Ель сербская (Оморика)",
    category: "hvoynye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 106,
    name: "Жасмин голоцветковый",
    category: "listvennye",
    price: 750,
    available: true,
    size: "C3",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 107,
    name: "Земляничное дерево (Арбутус)",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 108,
    name: "Ива ломкая «Булата»",
    category: "listvennye",
    price: 2250,
    available: true,
    size: "C10",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C10",
    description: ""
  },
  {
    id: 109,
    name: "Калина «Розеум» (Бульденеж)",
    category: "listvennye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 120,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 110,
    name: "Калина лавролистная",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 111,
    name: "Калина лавролистная «Ева Прайс»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 1940,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 112,
    name: "Кедр атласский",
    category: "hvoynye",
    price: 2550,
    available: true,
    size: "C10",
    qty: 455,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C10",
    description: ""
  },
  {
    id: 113,
    name: "Кедр атласский «Глаука»",
    category: "hvoynye",
    price: 3000,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 114,
    name: "Кедр атласский «Глаука Пендула»",
    category: "hvoynye",
    price: 3000,
    available: true,
    size: "C5",
    qty: 130,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 115,
    name: "Кедр гималайский (Деодара)",
    category: "hvoynye",
    price: 2550,
    available: true,
    size: "C10",
    qty: 345,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C10",
    description: ""
  },
  {
    id: 116,
    name: "Кедр гималайский «Пендула»",
    category: "hvoynye",
    price: 3000,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 117,
    name: "Кедр гималайский «Голден Горизонт»",
    category: "hvoynye",
    price: 3000,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 118,
    name: "Кедр гималайский «Филинг Блю»",
    category: "hvoynye",
    price: 3000,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 119,
    name: "Кедр ливанский",
    category: "hvoynye",
    price: 2550,
    available: true,
    size: "C7,5",
    qty: 840,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 120,
    name: "Керрия японская «Пленифлора»",
    category: "listvennye",
    price: 700,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 121,
    name: "Кизильник блестящий",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 122,
    name: "Кизильник Даммера",
    category: "listvennye",
    price: 750,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 123,
    name: "Кизильник Даммера «Миранда»",
    category: "listvennye",
    price: 750,
    available: true,
    size: "C3",
    qty: 1000,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 124,
    name: "Кипарис вечнозелёный «Тотем»",
    category: "hvoynye",
    price: 1350,
    available: true,
    size: "C3",
    qty: 3000,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 125,
    name: "Кипарис аризонский «Фастигиата»",
    category: "hvoynye",
    price: 1350,
    available: true,
    size: "C3",
    qty: 3500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 126,
    name: "Кипарис аризонский «Глаука»",
    category: "hvoynye",
    price: 1350,
    available: true,
    size: "C3",
    qty: 675,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 127,
    name: "Кипарисовик Лавсона «Вайт Спот»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 504,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 128,
    name: "Кипарисовик Лавсона «Ван Пелтс Блю»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1008,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 129,
    name: "Кипарисовик Лавсона «Ивон»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 504,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 130,
    name: "Кипарисовик тупой «Драхт»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 216,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 131,
    name: "Кипарисовик тупой «Нана Грацилис»",
    category: "hvoynye",
    price: 1050,
    available: true,
    size: "C3",
    qty: 504,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 132,
    name: "Котовник Фассена «Кит Кэт»",
    category: "mnogoletnie",
    price: 700,
    available: true,
    size: "C3",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 133,
    name: "Красивоплодник Бодиньера «Профьюжен»",
    category: "listvennye",
    price: 750,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 134,
    name: "Купрессоципарис Лейланда",
    category: "hvoynye",
    price: 900,
    available: true,
    size: "C3",
    qty: 11014,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 135,
    name: "Купрессоципарис Лейланда «2001»",
    category: "hvoynye",
    price: 900,
    available: true,
    size: "C3",
    qty: 9016,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Пирамидальная форма",
    description: ""
  },
  {
    id: 136,
    name: "Купрессоципарис Лейланда «Голд Райдер»",
    category: "hvoynye",
    price: 900,
    available: true,
    size: "C3",
    qty: 2016,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 137,
    name: "Лаванда узколистная «Нана Альба»",
    category: "mnogoletnie",
    price: 850,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 138,
    name: "Лаванда «Розеа»",
    category: "mnogoletnie",
    price: 850,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 139,
    name: "Лаванда узколистная «Хидкот»",
    category: "mnogoletnie",
    price: 825,
    available: true,
    size: "C3",
    qty: 600,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 140,
    name: "Лаванда гибридная «Гроссо»",
    category: "mnogoletnie",
    price: 750,
    available: true,
    size: "C3",
    qty: 450,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 141,
    name: "Лаванда узколистная «Розея»",
    category: "mnogoletnie",
    price: 750,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 142,
    name: "Лавровишня лузитанская «Ангустифолия»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 2000,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 143,
    name: "Лагерстрёмия индийская «Берри Дазл»",
    category: "listvennye",
    price: 1500,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Розовые соцветия",
    description: ""
  },
  {
    id: 144,
    name: "Лагерстрёмия индийская «Дабл Фичер»",
    category: "listvennye",
    price: 1500,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Ярко-розовые соцветия",
    description: ""
  },
  {
    id: 145,
    name: "Лагерстрёмия индийская «Рэд Император»",
    category: "listvennye",
    price: 1500,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Красные соцветия",
    description: ""
  },
  {
    id: 146,
    name: "Лагерстрёмия индийская «Блэк Даймонд Кримсон Рэд»",
    category: "listvennye",
    price: 2100,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Красные соцветия, тёмная листва",
    description: ""
  },
  {
    id: 147,
    name: "Лагерстрёмия индийская «Блэк Даймонд Блаш»",
    category: "listvennye",
    price: 2100,
    available: true,
    size: "C5",
    qty: 250,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Белые соцветия, тёмная листва",
    description: ""
  },
  {
    id: 148,
    name: "Лагерстрёмия индийская «Блэк Даймонд Шелл Пинк»",
    category: "listvennye",
    price: 2100,
    available: true,
    size: "C5",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Розовые соцветия, тёмная листва",
    description: ""
  },
  {
    id: 149,
    name: "Лох узколистный",
    category: "listvennye",
    price: 2250,
    available: true,
    size: "C10",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C10",
    description: ""
  },
  {
    id: 150,
    name: "Лох Эббинга",
    category: "listvennye",
    price: 1150,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 151,
    name: "Лох Эббинга «Гилт Эдж»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C3",
    qty: 400,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 152,
    name: "Лох Эббинга «Компакта»",
    category: "listvennye",
    price: 1150,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 153,
    name: "Лох Эббинга «Лаймлайт»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C3",
    qty: 160,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 154,
    name: "Лох Эббинга «Мерелин»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 155,
    name: "Лох Эббинга «Вивилег»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 700,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 156,
    name: "Магнолия крупноцветковая «Литл Джем»",
    category: "listvennye",
    price: 4000,
    available: true,
    size: "C7,5",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Вечнозелёная",
    description: ""
  },
  {
    id: 157,
    name: "Магнолия Лёбнера «Меррилл»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C7,5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Белые цветки",
    description: ""
  },
  {
    id: 158,
    name: "Магнолия Суланжа",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C7,5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Розово-белые цветки",
    description: ""
  },
  {
    id: 159,
    name: "Магнолия Суланжа «Джени»",
    category: "listvennye",
    price: 3000,
    available: true,
    size: "C7,5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Тёмно-розовые цветки",
    description: ""
  },
  {
    id: 160,
    name: "Магнолия Суланжа «Орхид»",
    category: "listvennye",
    price: 1500,
    available: true,
    size: "C7,5",
    qty: 120,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Ярко-розовые цветки",
    description: ""
  },
  {
    id: 161,
    name: "Магнолия «Сьюзан»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C7,5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Звёздчатая, розовые цветки",
    description: ""
  },
  {
    id: 162,
    name: "Магнолия Суланжа «Гелакси»",
    category: "listvennye",
    price: 1500,
    available: true,
    size: "C7,5",
    qty: 120,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Розовые цветки",
    description: ""
  },
  {
    id: 163,
    name: "Микробиота перекрёстнопарная",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 108,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 164,
    name: "Можжевельник виргинский «Хетц»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 2016,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 165,
    name: "Можжевельник виргинский «Грей Оул»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 166,
    name: "Можжевельник горизонтальный «Вилтони»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1000,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 167,
    name: "Можжевельник горизонтальный «Андорра Вариегата»",
    category: "hvoynye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 1400,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 168,
    name: "Можжевельник горизонтальный «Андорра Компакт»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1008,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 169,
    name: "Можжевельник горизонтальный «Принц Уэльский»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 3006,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 170,
    name: "Можжевельник казацкий «Блю Спаркл»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 171,
    name: "Можжевельник казацкий «Рокери Джем»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1600,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 172,
    name: "Можжевельник казацкий «Тамарисцифолия»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 9018,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 173,
    name: "Можжевельник китайский «Стрикта Вариегата»",
    category: "hvoynye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 174,
    name: "Можжевельник китайский «Блю Альпс»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 414,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 175,
    name: "Можжевельник обыкновенный «Голдшатц»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 176,
    name: "Можжевельник обыкновенный «Грин Карпет»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 216,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 177,
    name: "Можжевельник прибрежный «Блю Пасифик»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1616,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 178,
    name: "Можжевельник прибрежный «Шлягер»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 918,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 179,
    name: "Можжевельник Пфитцера «Кинг оф Спринг»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 702,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 180,
    name: "Можжевельник Пфитцера «Ауреа»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1008,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 181,
    name: "Можжевельник Пфитцера «Глаука»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1116,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 182,
    name: "Можжевельник Пфитцера «Голд Кост»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 3006,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 183,
    name: "Можжевельник Пфитцера «Голд Стар»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 6066,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 184,
    name: "Можжевельник Пфитцера «Минт Джулеп»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 8010,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 185,
    name: "Можжевельник Пфитцера «Олд Голд»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 6002,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 186,
    name: "Можжевельник Пфитцера «Пфитцериана Компакта»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1060,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 187,
    name: "Можжевельник скальный «Блю Эрроу»",
    category: "hvoynye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 15012,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 188,
    name: "Можжевельник скальный «Мунглоу»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 9018,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 189,
    name: "Можжевельник чешуйчатый «Блю Шведе»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 504,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 190,
    name: "Можжевельник чешуйчатый «Блю Карпет»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 918,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 191,
    name: "Можжевельник чешуйчатый «Мейери»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1008,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 192,
    name: "Можжевельник чешуйчатый «Холгер»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 504,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 193,
    name: "Мушмула японская",
    category: "listvennye",
    price: 1650,
    available: true,
    size: "C7,5",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 194,
    name: "Павловния войлочная",
    category: "listvennye",
    price: 2250,
    available: true,
    size: "C10",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C10",
    description: ""
  },
  {
    id: 195,
    name: "Падуб остролистный «Аргентеа Маргината»",
    category: "listvennye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 196,
    name: "Пахисандра верхушечная «Грин Карпет»",
    category: "mnogoletnie",
    price: 750,
    available: true,
    size: "C3",
    qty: 400,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 197,
    name: "Пахисандра верхушечная «Вариегата»",
    category: "mnogoletnie",
    price: 750,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 198,
    name: "Пираканта «Рэд Колумн»",
    category: "listvennye",
    price: 750,
    available: true,
    size: "C3",
    qty: 170,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 199,
    name: "Пихта корейская «Сильберлок»",
    category: "hvoynye",
    price: 4500,
    available: true,
    size: "C5",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 200,
    name: "Пихта Нордмана",
    category: "hvoynye",
    price: 1350,
    available: true,
    size: "C3",
    qty: 20,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 201,
    name: "Пузыреплодник калинолистный «Ангел Голд»",
    category: "listvennye",
    price: 700,
    available: true,
    size: "C3",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 202,
    name: "Пузыреплодник калинолистный «Мэджик Сансет»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 203,
    name: "Пузыреплодник калинолистный «Саммер Вайн»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 204,
    name: "Пузыреплодник калинолистный «Эмбер Джубили»",
    category: "listvennye",
    price: 1050,
    available: true,
    size: "C3",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 205,
    name: "Пузыреплодник калинолистный «Литл Девил»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 206,
    name: "Ринхоспермум жасминовидный",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Вечнозелёная ароматная лиана",
    description: ""
  },
  {
    id: 207,
    name: "Рододендрон «Гейша Парпл»",
    category: "listvennye",
    price: 1200,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Сиреневые цветки",
    description: ""
  },
  {
    id: 208,
    name: "Рододендрон «Марсель Менар»",
    category: "listvennye",
    price: 2250,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Фиолетовые цветки",
    description: ""
  },
  {
    id: 209,
    name: "Рододендрон «Нова Зембла»",
    category: "listvennye",
    price: 2250,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Красные цветки",
    description: ""
  },
  {
    id: 210,
    name: "Рододендрон «Рэд Джек»",
    category: "listvennye",
    price: 2250,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Красные цветки",
    description: ""
  },
  {
    id: 211,
    name: "Розмарин лекарственный «Корсикан Блю»",
    category: "mnogoletnie",
    price: 750,
    available: true,
    size: "C3",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 212,
    name: "Рябинник рябинолистный «Сэм»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 213,
    name: "Сирень обыкновенная «Мадам Лемуан»",
    category: "listvennye",
    price: 1150,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 214,
    name: "Сирень обыкновенная «Сенсация»",
    category: "listvennye",
    price: 1150,
    available: true,
    size: "C5",
    qty: 200,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 215,
    name: "Сирень обыкновенная «Чарльз Джоли»",
    category: "listvennye",
    price: 1150,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 216,
    name: "Скумпия кожевенная «Роял Парпл»",
    category: "listvennye",
    price: 1350,
    available: true,
    size: "C5",
    qty: 400,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 217,
    name: "Сосна горная «Бенджамин»",
    category: "hvoynye",
    price: 6000,
    available: true,
    size: "C7,5",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 218,
    name: "Сосна чёрная «Орегон Грин»",
    category: "hvoynye",
    price: 6000,
    available: true,
    size: "C7,5",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 219,
    name: "Сосна Гельдрейха «Компакт Джем»",
    category: "hvoynye",
    price: 6000,
    available: true,
    size: "C7,5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 220,
    name: "Сосна чёрная (Нигра)",
    category: "hvoynye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 1000,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 221,
    name: "Сосна алеппская",
    category: "hvoynye",
    price: 1800,
    available: true,
    size: "C10",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C10",
    description: ""
  },
  {
    id: 222,
    name: "Сосна горная «Малинки»",
    category: "hvoynye",
    price: 6000,
    available: true,
    size: "C7,5",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 223,
    name: "Сосна горная «Винтерголд»",
    category: "hvoynye",
    price: 6000,
    available: true,
    size: "C7,5",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 224,
    name: "Сосна горная «Карстенс Винтерголд»",
    category: "hvoynye",
    price: 6000,
    available: true,
    size: "C7,5",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 225,
    name: "Сосна горная «Мопс»",
    category: "hvoynye",
    price: 6000,
    available: true,
    size: "C7,5",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 226,
    name: "Сосна горная «Мугус»",
    category: "hvoynye",
    price: 900,
    available: true,
    size: "C3",
    qty: 504,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 227,
    name: "Сосна горная «Пумилио»",
    category: "hvoynye",
    price: 900,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 228,
    name: "Сосна горная «Винтерголд»",
    category: "hvoynye",
    price: 4000,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 229,
    name: "Сосна горная «Гном»",
    category: "hvoynye",
    price: 4000,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 230,
    name: "Сосна горная «Мопс»",
    category: "hvoynye",
    price: 4000,
    available: true,
    size: "C5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  },
  {
    id: 231,
    name: "Сосна обыкновенная",
    category: "hvoynye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 400,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 232,
    name: "Спирея японская «Голден Принцесс»",
    category: "listvennye",
    price: 700,
    available: true,
    size: "C3",
    qty: 800,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 233,
    name: "Спирея японская «Голдфлейм»",
    category: "listvennye",
    price: 700,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 234,
    name: "Спирея японская «Дабл Плей Биг-Бэнг Трейси»",
    category: "listvennye",
    price: 700,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 235,
    name: "Спирея японская «Литл Принцесс»",
    category: "listvennye",
    price: 700,
    available: true,
    size: "C3",
    qty: 800,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 236,
    name: "Спирея японская «Литл Флейм»",
    category: "listvennye",
    price: 700,
    available: true,
    size: "C3",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 237,
    name: "Спирея японская «Энтони Ватерер»",
    category: "listvennye",
    price: 700,
    available: true,
    size: "C3",
    qty: 700,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 238,
    name: "Стефанандра «Криспа»",
    category: "listvennye",
    price: 700,
    available: true,
    size: "C3",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 239,
    name: "Тамарикс",
    category: "listvennye",
    price: 1000,
    available: true,
    size: "C7,5",
    qty: 63,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 240,
    name: "Тамарикс четырёхтычинковый (Тетрандра)",
    category: "listvennye",
    price: 1000,
    available: true,
    size: "C7,5",
    qty: 2000,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 241,
    name: "Тис средний «Денсиформис»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 1008,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 242,
    name: "Тис средний «Хиксии»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 504,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 243,
    name: "Тис средний «Хиллии»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 1008,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 244,
    name: "Тис ягодный",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 308,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 245,
    name: "Тис ягодный «Давид»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 1512,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 246,
    name: "Тис ягодный «Репанденс»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 504,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 247,
    name: "Тис ягодный «Саммерголд»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 308,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 248,
    name: "Тис ягодный «Фастигиата Робуста»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 308,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 249,
    name: "Туя восточная «Ауреа Нана»",
    category: "hvoynye",
    price: 900,
    available: true,
    size: "C3",
    qty: 7022,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 250,
    name: "Туя западная «Литл Джайант»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 702,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 251,
    name: "Туя западная «Голден Брабант»",
    category: "hvoynye",
    price: 1100,
    available: true,
    size: "C3",
    qty: 504,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 252,
    name: "Туя западная «Голден Глоб»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 1008,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 253,
    name: "Туя западная «Мистер Боулинг Болл»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 702,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 254,
    name: "Туя западная «Рейнгольд»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 108,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 255,
    name: "Туя западная «Брабант»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 216,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 256,
    name: "Туя западная «Вудварди»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 1080,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 257,
    name: "Туя западная «Голден Таффет»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 216,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 258,
    name: "Туя западная «Даника»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 5004,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 259,
    name: "Туя западная «Мириам»",
    category: "hvoynye",
    price: 1150,
    available: true,
    size: "C3",
    qty: 1624,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 260,
    name: "Туя западная «Смарагд»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 13024,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 261,
    name: "Туя западная «Тини Тим»",
    category: "hvoynye",
    price: 750,
    available: true,
    size: "C3",
    qty: 2484,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 262,
    name: "Туя складчатая «Випкорд»",
    category: "hvoynye",
    price: 850,
    available: true,
    size: "C3",
    qty: 216,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 263,
    name: "Туя складчатая «Кагерс Бьюти»",
    category: "hvoynye",
    price: 1000,
    available: true,
    size: "C3",
    qty: 700,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 264,
    name: "Туя складчатая «Форевер Голди»",
    category: "hvoynye",
    price: 1100,
    available: true,
    size: "C3",
    qty: 616,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 265,
    name: "Фейхоа",
    category: "listvennye",
    price: 1200,
    available: true,
    size: "C7,5",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 266,
    name: "Хеномелес «Пинк Трейл»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 115,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 267,
    name: "Хеномелес «Рэд Трейл»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 120,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 268,
    name: "Чубушник «Сноубелл»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 269,
    name: "Чубушник «Вирджинал»",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 270,
    name: "Чубушник венечный",
    category: "listvennye",
    price: 900,
    available: true,
    size: "C3",
    qty: 100,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 271,
    name: "Эвкалипт «Бейби Блю»",
    category: "listvennye",
    price: 1150,
    available: true,
    size: "C3",
    qty: 50,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 272,
    name: "Эскаллония «Рубра Макранта»",
    category: "listvennye",
    price: 850,
    available: true,
    size: "C3",
    qty: 120,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C3",
    description: ""
  },
  {
    id: 273,
    name: "Юкка глориоза «Вариегата»",
    category: "mnogoletnie",
    price: 2550,
    available: true,
    size: "C7,5",
    qty: 500,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C7,5",
    description: ""
  },
  {
    id: 274,
    name: "Юкка рострата «Сапфир»",
    category: "mnogoletnie",
    price: 2850,
    available: true,
    size: "C5",
    qty: 300,
    image: "images/catalog/placeholder.jpg",
    gallery: [],
    short: "Контейнер C5",
    description: ""
  }
];

/* Названия категорий — можно менять подписи, но НЕ ключи */
const CATEGORIES = {
  hvoynye:     { title: "Хвойные",     icon: "images/site/7.jpg" },
  listvennye:  { title: "Лиственные",  icon: "images/site/8.jpg" },
  mnogoletnie: { title: "Многолетние", icon: "images/site/9.jpg" }
};
